"""Stable facade for professor-domain capabilities."""

from importlib import import_module
from .management import (
    ALLOWED_TITLES,
    PROFESSOR_EXPORT_COLUMNS,
    PROFESSOR_LEGACY_TEMPLATE_COLUMNS,
    PROFESSOR_TEMPLATE_COLUMNS,
    ParsedProfessorImport,
    build_professor_export,
    build_professor_template,
    is_valid_professor_email,
    normalize_professor_email,
    normalize_professor_payload,
    normalize_professor_title,
    parse_professor_import_file,
)
from .mutations import (
    ProfessorImportMutationResult,
    ProfessorMutationError,
    archive_professor_record,
    bulk_archive_professor_records,
    bulk_update_professor_tags_record,
    create_professor_record,
    create_professor_tag_record,
    delete_professor_tag_record,
    get_professor_tag_usage_snapshot,
    get_or_create_professor_by_email,
    get_professor_with_tags_or_raise,
    import_professor_records,
    load_or_create_tags_by_names,
    load_tags_by_ids,
    prepare_bulk_professor_archive_snapshot,
    prepare_bulk_professor_tags_snapshot,
    prepare_professor_import_snapshot,
    prepare_professor_tag_delete_snapshot,
    record_professor_event,
    restore_professor_record,
    set_professor_tags_record,
    sync_professor_tags,
    sync_professor_tags_by_names,
    update_professor_record,
)
from .normalization import (
    RECENT_PAPERS_MAX_ITEMS,
    normalize_recent_papers,
    normalize_research_direction,
)
from .samples import SAMPLE_PROFESSORS
from .schemas import (
    MAX_PERSONAL_NOTE_LENGTH,
    ProfessorActionResult,
    ProfessorBulkArchivePayload,
    ProfessorBulkTagsPayload,
    ProfessorBulkTagsResult,
    ProfessorDashboardItemRead,
    ProfessorDashboardStatus,
    ProfessorImportFileResult,
    ProfessorImportResult,
    ProfessorManagementItemRead,
    ProfessorNoteUpdatePayload,
    ProfessorNoteUpdateRead,
    ProfessorRead,
    ProfessorTagPayload,
    ProfessorTagRead,
    ProfessorTagUpdatePayload,
    ProfessorTagUsageProfessorRead,
    ProfessorTagUsageRead,
    ProfessorUpsertPayload,
)


_ENRICHMENT_EXPORTS = frozenset(
    {
        "CreateProfessorInformationEnrichmentJobRequest",
        "CreateProfessorInformationEnrichmentRequest",
        "ProfessorInformationEnrichmentActiveRead",
        "ProfessorInformationEnrichmentItemRead",
        "ProfessorInformationEnrichmentItemsPageRead",
        "ProfessorInformationEnrichmentJobActionRead",
        "ProfessorInformationEnrichmentJobRead",
        "apply_enrichment_to_professor",
        "create_professor_information_enrichment_job",
        "create_professor_information_enrichment_job_record",
        "delete_professor_information_enrichment_job_record",
        "finalize_professor_information_enrichment_job",
        "get_active_professor_information_enrichment_job",
        "get_missing_information_enrichment_fields",
        "get_professor_information_enrichment_job",
        "list_professor_information_enrichment_items",
        "list_professor_information_enrichment_items_page",
        "list_professor_information_enrichment_jobs",
        "request_professor_information_enrichment_cancel",
        "restore_professor_information_enrichment_job_record",
        "retry_failed_professor_information_enrichment_job",
        "retry_failed_professor_information_enrichment_job_record",
        "serialize_professor_information_enrichment_job",
    },
)


def __getattr__(name: str) -> object:
    if name not in _ENRICHMENT_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module("app.modules.professors.enrichment.public"), name)
    globals()[name] = value
    return value

__all__ = [
    "ALLOWED_TITLES",
    "CreateProfessorInformationEnrichmentJobRequest",
    "CreateProfessorInformationEnrichmentRequest",
    "MAX_PERSONAL_NOTE_LENGTH",
    "PROFESSOR_EXPORT_COLUMNS",
    "PROFESSOR_LEGACY_TEMPLATE_COLUMNS",
    "PROFESSOR_TEMPLATE_COLUMNS",
    "ParsedProfessorImport",
    "ProfessorActionResult",
    "ProfessorBulkArchivePayload",
    "ProfessorBulkTagsPayload",
    "ProfessorBulkTagsResult",
    "ProfessorDashboardItemRead",
    "ProfessorDashboardStatus",
    "ProfessorImportFileResult",
    "ProfessorImportMutationResult",
    "ProfessorImportResult",
    "ProfessorInformationEnrichmentActiveRead",
    "ProfessorInformationEnrichmentItemRead",
    "ProfessorInformationEnrichmentJobActionRead",
    "ProfessorInformationEnrichmentJobRead",
    "ProfessorManagementItemRead",
    "ProfessorMutationError",
    "ProfessorNoteUpdatePayload",
    "ProfessorNoteUpdateRead",
    "ProfessorRead",
    "ProfessorTagPayload",
    "ProfessorTagRead",
    "ProfessorTagUpdatePayload",
    "ProfessorTagUsageProfessorRead",
    "ProfessorTagUsageRead",
    "ProfessorUpsertPayload",
    "RECENT_PAPERS_MAX_ITEMS",
    "SAMPLE_PROFESSORS",
    "archive_professor_record",
    "apply_enrichment_to_professor",
    "build_professor_export",
    "build_professor_template",
    "bulk_archive_professor_records",
    "bulk_update_professor_tags_record",
    "create_professor_record",
    "create_professor_information_enrichment_job",
    "create_professor_information_enrichment_job_record",
    "create_professor_tag_record",
    "delete_professor_tag_record",
    "delete_professor_information_enrichment_job_record",
    "finalize_professor_information_enrichment_job",
    "get_active_professor_information_enrichment_job",
    "get_missing_information_enrichment_fields",
    "get_professor_information_enrichment_job",
    "get_professor_tag_usage_snapshot",
    "get_or_create_professor_by_email",
    "get_professor_with_tags_or_raise",
    "import_professor_records",
    "is_valid_professor_email",
    "list_professor_information_enrichment_items",
    "list_professor_information_enrichment_items_page",
    "list_professor_information_enrichment_jobs",
    "load_or_create_tags_by_names",
    "load_tags_by_ids",
    "normalize_professor_email",
    "normalize_professor_payload",
    "normalize_professor_title",
    "normalize_recent_papers",
    "normalize_research_direction",
    "parse_professor_import_file",
    "prepare_bulk_professor_archive_snapshot",
    "prepare_bulk_professor_tags_snapshot",
    "prepare_professor_import_snapshot",
    "prepare_professor_tag_delete_snapshot",
    "record_professor_event",
    "request_professor_information_enrichment_cancel",
    "restore_professor_record",
    "restore_professor_information_enrichment_job_record",
    "retry_failed_professor_information_enrichment_job",
    "retry_failed_professor_information_enrichment_job_record",
    "serialize_professor_information_enrichment_job",
    "set_professor_tags_record",
    "sync_professor_tags",
    "sync_professor_tags_by_names",
    "update_professor_record",
]
