"""Stable facade for professor information-enrichment capabilities."""

from .schemas import (
    CreateProfessorInformationEnrichmentJobRequest,
    CreateProfessorInformationEnrichmentRequest,
    ProfessorInformationEnrichmentActiveRead,
    ProfessorInformationEnrichmentItemRead,
    ProfessorInformationEnrichmentJobActionRead,
    ProfessorInformationEnrichmentJobRead,
)
from .service import (
    apply_enrichment_to_professor,
    create_professor_information_enrichment_job,
    create_professor_information_enrichment_job_record,
    delete_professor_information_enrichment_job_record,
    finalize_professor_information_enrichment_job,
    get_active_professor_information_enrichment_job,
    get_missing_information_enrichment_fields,
    get_professor_information_enrichment_job,
    list_professor_information_enrichment_items,
    list_professor_information_enrichment_jobs,
    request_professor_information_enrichment_cancel,
    restore_professor_information_enrichment_job_record,
    retry_failed_professor_information_enrichment_job,
    retry_failed_professor_information_enrichment_job_record,
    serialize_professor_information_enrichment_job,
)

__all__ = [
    "CreateProfessorInformationEnrichmentJobRequest",
    "CreateProfessorInformationEnrichmentRequest",
    "ProfessorInformationEnrichmentActiveRead",
    "ProfessorInformationEnrichmentItemRead",
    "ProfessorInformationEnrichmentJobActionRead",
    "ProfessorInformationEnrichmentJobRead",
    "apply_enrichment_to_professor",
    "create_professor_information_enrichment_job",
    "create_professor_information_enrichment_job_record",
    "delete_professor_information_enrichment_job_record",
    "finalize_professor_information_enrichment_job",
    "get_active_professor_information_enrichment_job",
    "get_missing_information_enrichment_fields",
    "get_professor_information_enrichment_job",
    "list_professor_information_enrichment_items",
    "list_professor_information_enrichment_jobs",
    "request_professor_information_enrichment_cancel",
    "restore_professor_information_enrichment_job_record",
    "retry_failed_professor_information_enrichment_job",
    "retry_failed_professor_information_enrichment_job_record",
    "serialize_professor_information_enrichment_job",
]
