"""Compatibility exports for migrated professor mutation services."""

from app.modules.professors.mutations import (
    ProfessorImportMutationResult,
    ProfessorMutationError,
    archive_professor_record,
    bulk_archive_professor_records,
    bulk_update_professor_tags_record,
    create_professor_record,
    create_professor_tag_record,
    delete_professor_tag_record,
    get_professor_tag_usage_snapshot,
    get_professor_with_tags_or_raise,
    import_professor_records,
    load_or_create_tags_by_names,
    load_tags_by_ids,
    prepare_bulk_professor_archive_snapshot,
    prepare_bulk_professor_tags_snapshot,
    prepare_professor_import_snapshot,
    prepare_professor_tag_delete_snapshot,
    record_professor_event,
    restore_professor_record,
    set_professor_tags_record,
    sync_professor_tags,
    sync_professor_tags_by_names,
    update_professor_record,
)

__all__ = [
    "ProfessorImportMutationResult",
    "ProfessorMutationError",
    "archive_professor_record",
    "bulk_archive_professor_records",
    "bulk_update_professor_tags_record",
    "create_professor_record",
    "create_professor_tag_record",
    "delete_professor_tag_record",
    "get_professor_tag_usage_snapshot",
    "get_professor_with_tags_or_raise",
    "import_professor_records",
    "load_or_create_tags_by_names",
    "load_tags_by_ids",
    "prepare_bulk_professor_archive_snapshot",
    "prepare_bulk_professor_tags_snapshot",
    "prepare_professor_import_snapshot",
    "prepare_professor_tag_delete_snapshot",
    "record_professor_event",
    "restore_professor_record",
    "set_professor_tags_record",
    "sync_professor_tags",
    "sync_professor_tags_by_names",
    "update_professor_record",
]
