"""Public entry point for LLM capabilities."""

from . import runtime as _runtime
from .adaptation.endpoint import (
    EndpointKind,
    ResponseEnvelopeClassification,
    classify_response_envelope,
    endpoint_adaptation_lock,
    endpoint_candidates,
    get_cached_endpoint_kind,
    invalidate_endpoint_adaptation,
    record_endpoint_adaptation,
)
from .adaptation.structured_output import (
    PROMPT_ONLY_CACHE_TTL,
    STRUCTURED_OUTPUT_PROBE_VERSION,
    StructuredOutputMode,
    ensure_structured_output_adaptation,
    get_cached_structured_output_mode,
    invalidate_structured_output_adaptation,
    is_structured_output_protocol_rejection,
    probe_structured_output_mode,
    record_structured_output_adaptation,
    structured_output_adaptation_lock,
)
from .adaptation.thinking import (
    THINKING_DISABLE_CANDIDATES,
    THINKING_PROTOCOL_ERROR_KEYWORDS,
    ThinkingAdaptationFailed,
    adapt_failure_message_for_thinking_error,
    ensure_thinking_adaptation,
    get_cached_extra_body,
    invalidate_thinking_adaptation,
    is_thinking_mode_protocol_error,
    merge_extra_body,
    probe_and_learn_extra_body,
    record_thinking_adaptation,
    resolve_thinking_extra_body,
    strip_thinking_keys,
)
from .runtime import *  # noqa: F403
from .schemas import (
    LLMProfileBase,
    LLMProfileCreate,
    LLMProfileModelsResult,
    LLMProfileRead,
    LLMProfileTestResult,
    LLMProfileUpdate,
)

__all__ = [
    *_runtime.__all__,
    "EndpointKind",
    "LLMProfileBase",
    "LLMProfileCreate",
    "LLMProfileModelsResult",
    "LLMProfileRead",
    "LLMProfileTestResult",
    "LLMProfileUpdate",
    "PROMPT_ONLY_CACHE_TTL",
    "ResponseEnvelopeClassification",
    "STRUCTURED_OUTPUT_PROBE_VERSION",
    "StructuredOutputMode",
    "THINKING_DISABLE_CANDIDATES",
    "THINKING_PROTOCOL_ERROR_KEYWORDS",
    "ThinkingAdaptationFailed",
    "adapt_failure_message_for_thinking_error",
    "classify_response_envelope",
    "endpoint_adaptation_lock",
    "endpoint_candidates",
    "ensure_structured_output_adaptation",
    "ensure_thinking_adaptation",
    "get_cached_endpoint_kind",
    "get_cached_extra_body",
    "get_cached_structured_output_mode",
    "invalidate_endpoint_adaptation",
    "invalidate_structured_output_adaptation",
    "invalidate_thinking_adaptation",
    "is_structured_output_protocol_rejection",
    "is_thinking_mode_protocol_error",
    "merge_extra_body",
    "probe_and_learn_extra_body",
    "probe_structured_output_mode",
    "record_endpoint_adaptation",
    "record_structured_output_adaptation",
    "record_thinking_adaptation",
    "resolve_thinking_extra_body",
    "strip_thinking_keys",
    "structured_output_adaptation_lock",
]
