"""Compatibility exports for migrated professor schemas."""

from app.modules.professors.schemas import (
    MAX_PERSONAL_NOTE_LENGTH,
    ProfessorActionResult,
    ProfessorBulkArchivePayload,
    ProfessorBulkTagsPayload,
    ProfessorBulkTagsResult,
    ProfessorDashboardItemRead,
    ProfessorDashboardStatus,
    ProfessorImportFileResult,
    ProfessorImportResult,
    ProfessorManagementItemRead,
    ProfessorNoteUpdatePayload,
    ProfessorNoteUpdateRead,
    ProfessorRead,
    ProfessorTagPayload,
    ProfessorTagRead,
    ProfessorTagUpdatePayload,
    ProfessorTagUsageProfessorRead,
    ProfessorTagUsageRead,
    ProfessorUpsertPayload,
)

__all__ = [
    "MAX_PERSONAL_NOTE_LENGTH",
    "ProfessorActionResult",
    "ProfessorBulkArchivePayload",
    "ProfessorBulkTagsPayload",
    "ProfessorBulkTagsResult",
    "ProfessorDashboardItemRead",
    "ProfessorDashboardStatus",
    "ProfessorImportFileResult",
    "ProfessorImportResult",
    "ProfessorManagementItemRead",
    "ProfessorNoteUpdatePayload",
    "ProfessorNoteUpdateRead",
    "ProfessorRead",
    "ProfessorTagPayload",
    "ProfessorTagRead",
    "ProfessorTagUpdatePayload",
    "ProfessorTagUsageProfessorRead",
    "ProfessorTagUsageRead",
    "ProfessorUpsertPayload",
]
