from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Final, Literal


RiskLevel = Literal["L0", "L1", "L2", "L3"]
Availability = Literal["available", "planned", "ui_only"]


@dataclass(frozen=True, slots=True)
class Capability:
    command: str
    summary: str
    risk_level: RiskLevel
    availability: Availability
    mutates: bool = False
    external_action: bool = False
    requires_plan: bool = False
    long_running: bool = False
    guide_topic: str = "overview"
    unavailable_reason: str | None = None

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


CAPABILITIES: Final[tuple[Capability, ...]] = (
    Capability("version", "查看 CLI 与协议版本", "L0", "available"),
    Capability("status", "查看桌面应用和本地服务状态", "L0", "available"),
    Capability("doctor", "检查 CLI、Skill、运行文件和本地服务", "L0", "available"),
    Capability("guide", "读取 Agent 使用说明", "L0", "available"),
    Capability("capabilities", "读取当前命令能力和风险信息", "L0", "available"),
    Capability("professors.list", "分页查询或读取全部导师档案", "L0", "available"),
    Capability("professors.get", "按 ID 读取导师完整档案", "L0", "available"),
    Capability("professors.tags.list", "读取导师标签", "L0", "available"),
    Capability("professors.tags.usage", "读取一个标签及其关联导师", "L0", "available"),
    Capability("professors.create", "新增一位导师", "L1", "available", mutates=True),
    Capability("professors.update", "局部修改一位导师", "L1", "available", mutates=True),
    Capability("professors.archive", "将一位导师移入回收站", "L1", "available", mutates=True),
    Capability("professors.restore", "恢复一位已归档导师", "L1", "available", mutates=True),
    Capability("professors.tags.create", "新增导师标签", "L1", "available", mutates=True),
    Capability("professors.tags.set", "设置一位导师的全部标签", "L1", "available", mutates=True),
    Capability(
        "professors.tags.prepare-bulk",
        "生成批量追加、移除或替换导师标签的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="safety",
    ),
    Capability(
        "professors.prepare-bulk-archive",
        "生成批量移入导师回收站的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="safety",
    ),
    Capability(
        "professors.tags.prepare-delete",
        "生成删除导师标签及解除关联的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="safety",
    ),
    Capability(
        "professors.import",
        "从 CSV 或 XLSX 生成导师导入预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="safety",
    ),
    Capability(
        "professors.export",
        "导出导师表格",
        "L0",
        "available",
    ),
    Capability(
        "professors.community.catalog",
        "读取或刷新社区导师目录",
        "L1",
        "available",
        external_action=True,
        guide_topic="community",
    ),
    Capability(
        "professors.community.records",
        "读取选定学院的社区导师及本地比对结果",
        "L0",
        "available",
        guide_topic="community",
    ),
    Capability(
        "professors.community.preview",
        "预览指定社区导师与本地档案的字段差异",
        "L0",
        "available",
        guide_topic="community",
    ),
    Capability(
        "professors.community.import",
        "生成社区导师导入的字段选择、冲突处理和确认计划",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="community",
    ),
    Capability(
        "professors.community.export-package",
        "导出可提交给社区的导师共享包",
        "L0",
        "available",
        guide_topic="community",
    ),
    Capability(
        "communications.threads.list",
        "按已发送、已回复、身份和导师筛选通信线程",
        "L0",
        "available",
        guide_topic="communications",
    ),
    Capability(
        "communications.threads.get",
        "读取一个通信线程及其邮件，可按需包含正文",
        "L0",
        "available",
        guide_topic="communications",
    ),
    Capability(
        "communications.messages.list",
        "分页或完整读取发件、收件和草稿记录",
        "L0",
        "available",
        guide_topic="communications",
    ),
    Capability(
        "communications.messages.get",
        "按 ID 读取一封邮件的完整正文",
        "L0",
        "available",
        guide_topic="communications",
    ),
    Capability(
        "communications.messages.export",
        "把大量邮件和完整正文导出为 JSONL",
        "L0",
        "available",
        guide_topic="communications",
    ),
    Capability(
        "communications.sync",
        "手动同步邮箱通信记录",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="communications",
    ),
    Capability("templates.list", "查询邮件模板", "L0", "available"),
    Capability("templates.get", "按 ID 读取完整模板内容", "L0", "available"),
    Capability(
        "templates.import-file",
        "解析本地 DOCX、HTML、Markdown 或文本邮件模板，不会保存或发送",
        "L0",
        "available",
    ),
    Capability("templates.create", "新增邮件模板", "L1", "available", mutates=True),
    Capability("templates.update", "局部修改邮件模板", "L1", "available", mutates=True),
    Capability("templates.duplicate", "复制邮件模板", "L1", "available", mutates=True),
    Capability("templates.set-default", "设为全局默认邮件模板", "L1", "available", mutates=True),
    Capability("templates.restore", "恢复已归档邮件模板", "L1", "available", mutates=True),
    Capability(
        "templates.prepare-archive",
        "生成邮件模板归档的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="sending",
    ),
    Capability(
        "materials.list",
        "查询可作为 AI 参考或附件的材料元数据",
        "L0",
        "available",
        guide_topic="materials",
    ),
    Capability(
        "materials.get",
        "按 ID 读取材料元数据和可选的已提取文本",
        "L0",
        "available",
        guide_topic="materials",
    ),
    Capability(
        "materials.upload",
        "从本地文件上传 AI 参考材料或邮件附件",
        "L1",
        "available",
        mutates=True,
        guide_topic="materials",
    ),
    Capability(
        "materials.set-primary",
        "设置一份可提取文本的默认 AI 参考材料",
        "L1",
        "available",
        mutates=True,
        guide_topic="materials",
    ),
    Capability(
        "materials.download",
        "下载已保存的材料文件",
        "L0",
        "available",
        guide_topic="materials",
    ),
    Capability(
        "materials.prepare-delete",
        "生成材料删除的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="materials",
    ),
    Capability("identities.list", "查询发件身份的脱敏视图", "L0", "available"),
    Capability("identities.get", "按 ID 读取发件身份的脱敏视图", "L0", "available"),
    Capability(
        "identities.update-settings",
        "修改发件身份的显示名、写信策略和发送频率，不会读取或修改连接与密码",
        "L1",
        "available",
        mutates=True,
        guide_topic="identities",
    ),
    Capability(
        "identities.set-default",
        "设为默认发件身份",
        "L1",
        "available",
        mutates=True,
        guide_topic="identities",
    ),
    Capability(
        "identities.set-default-template",
        "设置或清除某个发件身份的默认邮件模板",
        "L1",
        "available",
        mutates=True,
        guide_topic="identities",
    ),
    Capability(
        "identities.test-smtp",
        "使用已保存的 SMTP 凭据测试发件连接，不返回密码",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        guide_topic="identities",
    ),
    Capability(
        "identities.test-imap",
        "使用已保存的 IMAP 凭据测试收件连接，不返回密码",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        guide_topic="identities",
    ),
    Capability(
        "identities.credentials",
        "创建或删除发件身份，以及编辑邮件服务器、账号和密码",
        "L1",
        "ui_only",
        mutates=True,
        unavailable_reason="为避免密码出现在 Agent 对话、命令行历史或进程参数中，邮件服务器、账号和凭据只能在桌面端安全录入。",
    ),
    Capability("llm-profiles.list", "查询模型配置的脱敏视图", "L0", "available"),
    Capability("llm-profiles.get", "按 ID 读取模型配置的脱敏视图", "L0", "available"),
    Capability(
        "llm-profiles.update-settings",
        "修改模型配置名称、模型名、温度和输出 Token 上限，不会读取或修改服务地址和 API Key",
        "L1",
        "available",
        mutates=True,
        guide_topic="llm-profiles",
    ),
    Capability(
        "llm-profiles.set-default",
        "切换默认模型配置，不会显示 API Key",
        "L1",
        "available",
        mutates=True,
        guide_topic="llm-profiles",
    ),
    Capability(
        "llm-profiles.models",
        "使用已保存的凭据读取模型列表，不会显示 API Key",
        "L1",
        "available",
        external_action=True,
        guide_topic="llm-profiles",
    ),
    Capability(
        "llm-profiles.test",
        "使用已保存的凭据测试模型连接；可能消耗少量 Token，不会显示 API Key",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        guide_topic="llm-profiles",
    ),
    Capability(
        "llm-profiles.write",
        "创建或删除模型配置，以及编辑服务提供方、服务地址、提示词模板和 API Key",
        "L1",
        "ui_only",
        mutates=True,
        unavailable_reason="为避免 API Key 出现在 Agent 对话、命令行历史或进程参数中，模型服务地址、提示词模板和凭据只能在桌面端安全录入。",
    ),
    Capability(
        "matching.jobs.list",
        "分页查询当前或回收站中的匹配分析任务",
        "L0",
        "available",
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.get",
        "读取一个匹配分析任务的状态、进度和 Token 用量",
        "L0",
        "available",
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.items",
        "读取匹配分析任务中每位导师的状态、分数和失败原因",
        "L0",
        "available",
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.create",
        "创建异步匹配分析任务；会调用指定 LLM，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.cancel",
        "请求取消排队中或运行中的匹配分析任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.retry-failed",
        "为失败或已取消的导师项创建新的异步匹配分析任务",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.delete",
        "将已结束的匹配分析任务移入回收站",
        "L1",
        "available",
        mutates=True,
        guide_topic="matching",
    ),
    Capability(
        "matching.jobs.restore",
        "恢复回收站中的匹配分析任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="matching",
    ),
    Capability("drafts.get", "按任务 ID 读取草稿、参考材料和附件", "L0", "available", guide_topic="drafts"),
    Capability(
        "drafts.generate",
        "按导师、身份、模板、参考材料和附件生成 draft_only 草稿",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="drafts",
    ),
    Capability(
        "drafts.save",
        "保存手工主题、正文和附件；不会发送",
        "L1",
        "available",
        mutates=True,
        guide_topic="drafts",
    ),
    Capability(
        "drafts.regenerate",
        "按当前模板配置重新渲染或调用 AI 改写草稿；不会发送",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="drafts",
    ),
    Capability(
        "drafts.rewrite",
        "将指定草稿文本交给已配置模型改写；不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="drafts",
    ),
    Capability(
        "drafts.prepare-send",
        "为一封最终草稿创建 30 分钟有效的一次性发送或排程计划",
        "L3",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="sending",
    ),
    Capability("campaigns.list", "分页查询当前或回收站中的批量活动", "L0", "available", guide_topic="campaigns"),
    Capability("campaigns.get", "读取一个批量活动的状态、草稿和发送进度", "L0", "available", guide_topic="campaigns"),
    Capability(
        "campaigns.resend-context",
        "读取旧活动可重新发起的导师、原模板、材料和警告",
        "L0",
        "available",
        guide_topic="campaigns",
    ),
    Capability("campaigns.items", "分页读取活动中的导师、草稿状态和主题", "L0", "available", guide_topic="campaigns"),
    Capability(
        "campaigns.create",
        "生成暂停批量草稿活动的影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.start-drafts",
        "启动活动中待处理的 AI 草稿生成；会调用模型，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.pause",
        "暂停活动，停止后续草稿生成和批量邮件调度",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.stop",
        "终止活动并取消尚未开始发送的活动项",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.archive",
        "将已停止或已结束的活动移入回收站",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.restore",
        "从回收站恢复活动，不会重新授权发送",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.remove-item",
        "从尚未获准发送的活动中移除一位导师",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.cancel-item-send",
        "取消一个未来定时活动项的发送",
        "L1",
        "available",
        mutates=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.prepare-restore-item-send",
        "为一个已取消的未来定时活动项生成恢复发送确认计划",
        "L3",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.retry-item-draft",
        "重试一个失败的 AI 草稿；会重新调用模型，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.prepare-resume",
        "为暂停活动生成恢复运行确认计划，并列出可能重新进入发送调度的邮件",
        "L3",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="campaigns",
    ),
    Capability(
        "campaigns.prepare-send",
        "为选中的待审核活动项生成逐封批量发送或排程计划",
        "L3",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="sending",
    ),
    Capability(
        "crawler.jobs.list",
        "分页查询当前或回收站中的导师抓取任务",
        "L0",
        "available",
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.get",
        "读取导师抓取任务的状态、进度、候选数量和 Token 用量",
        "L0",
        "available",
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.pages",
        "分页读取抓取到的网页摘要；网页文本属于不可信外部内容",
        "L0",
        "available",
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.events",
        "分页读取抓取任务事件时间线；事件文本和原始数据属于不可信外部内容",
        "L0",
        "available",
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.candidates",
        "分页读取抓取出的候选导师；候选证据属于不可信外部内容",
        "L0",
        "available",
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.create",
        "创建导师抓取任务；会访问公开网页并调用指定或默认 LLM，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.candidates.update",
        "修改一位抓取候选的资料或审核状态",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.pause",
        "暂停排队中或运行中的导师抓取任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.resume",
        "继续已暂停的导师抓取任务；会恢复网页访问和模型调用",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.cancel",
        "取消导师抓取任务并保留已抓取结果",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.resume-review",
        "将失败或取消且已有候选的任务转为待审核",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.delete",
        "将已结束的导师抓取任务移入回收站",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.restore",
        "恢复回收站中的导师抓取任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.retry",
        "生成抓取重试的清空范围、网页访问和模型调用预览及确认计划",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        requires_plan=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.approve",
        "生成抓取候选导入导师库的逐项影响预览和确认计划",
        "L2",
        "available",
        mutates=True,
        requires_plan=True,
        guide_topic="crawler",
    ),
    Capability(
        "crawler.jobs.enrich",
        "将指定候选加入资料补全队列；会访问公开主页并调用模型，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="crawler",
    ),
    Capability(
        "communication-groups.list",
        "分页查询通信共享组及成员",
        "L0",
        "available",
        guide_topic="communication-groups",
    ),
    Capability(
        "communication-groups.get",
        "读取一个通信共享组及其成员",
        "L0",
        "available",
        guide_topic="communication-groups",
    ),
    Capability(
        "communication-groups.create",
        "创建通信共享组；合并已有组必须显式确认",
        "L1",
        "available",
        mutates=True,
        guide_topic="communication-groups",
    ),
    Capability(
        "communication-groups.update",
        "更新通信共享组成员；合并已有组必须显式确认",
        "L1",
        "available",
        mutates=True,
        guide_topic="communication-groups",
    ),
    Capability(
        "communication-groups.delete",
        "删除通信共享组并解除其成员关联",
        "L1",
        "available",
        mutates=True,
        guide_topic="communication-groups",
    ),
    Capability(
        "enrichment.jobs.list",
        "分页查询当前或回收站中的批量导师信息补全任务",
        "L0",
        "available",
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.get",
        "读取导师信息补全任务的状态、进度和 Token 用量",
        "L0",
        "available",
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.items",
        "读取补全任务中每位导师的状态、已补全字段和失败原因",
        "L0",
        "available",
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.create",
        "创建批量导师信息补全任务；会访问导师主页并调用指定 LLM，但不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.cancel",
        "请求取消排队中或运行中的导师信息补全任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.retry-failed",
        "为失败或已取消的导师项创建新的批量信息补全任务",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.delete",
        "将已结束的导师信息补全任务移入回收站",
        "L1",
        "available",
        mutates=True,
        guide_topic="enrichment",
    ),
    Capability(
        "enrichment.jobs.restore",
        "恢复回收站中的导师信息补全任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="enrichment",
    ),
    Capability(
        "test-email.status",
        "查看指定发件身份是否已成功发送过测试邮件",
        "L0",
        "available",
        guide_topic="test-email",
    ),
    Capability(
        "test-email.get",
        "读取发给自己的测试邮件草稿、附件选项和历史",
        "L0",
        "available",
        guide_topic="test-email",
    ),
    Capability(
        "test-email.generate",
        "生成测试邮件草稿；AI 模式会调用已保存的模型配置",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        guide_topic="test-email",
    ),
    Capability(
        "test-email.save",
        "保存测试邮件草稿和附件选择，不会发送邮件",
        "L1",
        "available",
        mutates=True,
        guide_topic="test-email",
    ),
    Capability(
        "test-email.prepare-send",
        "生成发送到当前身份自己邮箱的测试邮件确认计划",
        "L3",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="test-email",
    ),
    Capability(
        "dashboard.overview",
        "读取指定身份的导师匹配、发送、回信和待处理概览",
        "L0",
        "available",
        guide_topic="insights",
    ),
    Capability(
        "usage.records",
        "分页读取已记录的 LLM Token 用量",
        "L0",
        "available",
        guide_topic="insights",
    ),
    Capability(
        "usage.chart",
        "读取指定时间范围的 Token 用量趋势",
        "L0",
        "available",
        guide_topic="insights",
    ),
    Capability(
        "usage.visualization",
        "读取 Token 汇总、分布、模型排行和近期记录",
        "L0",
        "available",
        guide_topic="insights",
    ),
    Capability(
        "diagnostics.logs",
        "按筛选读取已脱敏的操作诊断日志",
        "L0",
        "available",
        guide_topic="diagnostics",
    ),
    Capability(
        "diagnostics.export",
        "导出已脱敏的操作日志与启动诊断信息",
        "L0",
        "available",
        guide_topic="diagnostics",
    ),
    Capability(
        "diagnostics.crawler-debug",
        "导出已脱敏的抓取任务调试 JSONL",
        "L0",
        "available",
        guide_topic="diagnostics",
    ),
    Capability(
        "settings.get",
        "读取不含凭据的运行设置",
        "L0",
        "available",
        guide_topic="settings",
    ),
    Capability(
        "settings.update",
        "修改抓取、匹配和草稿生成的运行设置",
        "L1",
        "available",
        mutates=True,
        guide_topic="settings",
    ),
    Capability(
        "workspaces.get",
        "读取一位导师在指定身份下的邮件工作区、草稿和通信记录",
        "L0",
        "available",
        guide_topic="workspaces",
    ),
    Capability(
        "workspaces.ensure-task",
        "确保一位导师有可继续处理的手动邮件任务；不会发送邮件",
        "L1",
        "available",
        mutates=True,
        guide_topic="workspaces",
    ),
    Capability(
        "workspaces.refresh-replies",
        "按通信共享范围同步一位导师的回信；会连接已配置的 IMAP 邮箱",
        "L1",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="workspaces",
    ),
    Capability(
        "tasks.cancel-schedule",
        "取消单封任务的定时状态并回到待审核草稿",
        "L1",
        "available",
        mutates=True,
        guide_topic="tasks",
    ),
    Capability(
        "tasks.continue-manually",
        "为已因批量活动停止而取消的任务创建可继续处理的手动任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="tasks",
    ),
    Capability(
        "tasks.start-follow-up",
        "为已发送或已回信任务创建一封跟进草稿任务",
        "L1",
        "available",
        mutates=True,
        guide_topic="tasks",
    ),
    Capability(
        "tasks.set-primary-material",
        "切换单封任务的 AI 参考材料并重新生成草稿；AI 模式会调用模型",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="tasks",
    ),
    Capability(
        "tasks.set-outreach-config",
        "修改单封任务的模板、生成模式或本次模板文本，不会发送邮件",
        "L1",
        "available",
        mutates=True,
        guide_topic="tasks",
    ),
    Capability(
        "tasks.calculate-match",
        "调用模型重新计算单封任务与导师的匹配度，不会发送邮件",
        "L2",
        "available",
        mutates=True,
        external_action=True,
        long_running=True,
        guide_topic="tasks",
    ),
    Capability(
        "plans.show",
        "读取发送计划、最终正文和确认状态",
        "L0",
        "available",
        guide_topic="sending",
    ),
    Capability(
        "plans.execute",
        "在用户明确确认后一次性执行发送或排程计划",
        "L3",
        "available",
        mutates=True,
        external_action=True,
        requires_plan=True,
        guide_topic="sending",
    ),
    Capability(
        "plans.cancel",
        "取消尚未执行的发送计划",
        "L1",
        "available",
        mutates=True,
        guide_topic="sending",
    ),
)


def list_capabilities(command: str | None = None) -> list[dict[str, object]]:
    items = CAPABILITIES
    if command:
        normalized = command.strip().lower()
        items = tuple(
            item
            for item in CAPABILITIES
            if item.command == normalized or item.command.startswith(f"{normalized}.")
        )
    return [item.to_dict() for item in items]
