"""Compatibility exports for the migrated professor HTTP adapter."""

from app.modules.professors.api import (
    archive_professor,
    bulk_archive_professors,
    bulk_update_professor_tags,
    create_professor,
    create_professor_tag,
    delete_professor_tag,
    download_professor_template,
    export_professors,
    get_professor,
    get_professor_tag_usage,
    import_professors_from_file,
    import_sample_professors,
    list_professor_tags,
    list_professors,
    list_professors_for_management,
    restore_professor,
    router,
    trigger_crawler,
    update_professor,
    update_professor_personal_note,
    update_professor_tags,
)

__all__ = [
    "archive_professor",
    "bulk_archive_professors",
    "bulk_update_professor_tags",
    "create_professor",
    "create_professor_tag",
    "delete_professor_tag",
    "download_professor_template",
    "export_professors",
    "get_professor",
    "get_professor_tag_usage",
    "import_professors_from_file",
    "import_sample_professors",
    "list_professor_tags",
    "list_professors",
    "list_professors_for_management",
    "restore_professor",
    "router",
    "trigger_crawler",
    "update_professor",
    "update_professor_personal_note",
    "update_professor_tags",
]
